### ISSUE TITLE
Use message id as a identifier for duplication check mechanism

### ISSUE THREAD

**Issue by jakubuid** [WalletConnect/WalletConnectUnity#103]
Currently, the client JSON RPC duplication mechanism uses the client JSON RPC ID as a unique identifier to detect duplicated client JSON RPC requests.

Since this approach doesn't guarantee the uniqueness of IDs and there's a chance of conflicts a new approach with higher entropy is introduced.

The new id is a `sha256` function of the decrypted payload of the client request:
`message_id = sha256(decrypted_payload)`

**Testing:**
- Make sure that backward compatibility is not broken
- Cross-platform testing (js, swift, kotlin, flutter)

**Comment by gigajuwels** [comment]
Shouldn't this issue be moved to [WalletConnectSharp](https://github.com/WalletConnect/WalletConnectSharp/issues), since JSON RPC IDs are generated inside the `Core` and `Network` module? The Unity project cannot access/modify this behavior directly.

Here is where the id is currently generated in `WalletConnectSharp`:
* [TypeMessageHandler.SendRequest](https://github.com/WalletConnect/WalletConnectSharp/blob/2.0/WalletConnectSharp.Core/Controllers/TypedMessageHandler.cs#L308)
* [JsonRpcRequest constructor (if `id` is null)](https://github.com/WalletConnect/WalletConnectSharp/blob/2.0/Core%20Modules/WalletConnectSharp.Network/Models/JsonRpcRequest.cs#L80)
* [RpcPayloadId.Generate (can be replaced with new logic)](https://github.com/WalletConnect/WalletConnectSharp/blob/2.0/Core%20Modules/WalletConnectSharp.Events/Utils/RpcPayloadId.cs#L18)

**Comment by jakubuid** [comment]
Yeah, I'm not aware of the Unity repo structure, so if it makes more sense to put this issue into Sharp repo, let's do it.

**Comment by skibitsky** [comment]
Moved it into WalletConnectSharp [#130](https://github.com/WalletConnect/WalletConnectSharp/issues/130)
