### ISSUE TITLE
Unity Editor gets closed after pressing stop

### ISSUE THREAD

**Issue by KiranJodhani** [WalletConnect/WalletConnectUnity#104]
Hi
When I press stop button . Unity editor closes.
I downloaded this repo
Opened it in Unity 2021.3.6
Opened scene SimpleUnityDapp
Pressed play with default settings
Pressed stop button. 
Unity editor closed.

**Comment by skibitsky** [comment]
This is caused by disposal deadlock.
![Dispose Logs](https://github.com/WalletConnect/WalletConnectUnity/assets/15127974/c2f5ba6f-d1bd-44d4-ab5a-3589003333cb)


The temporary workaround is to remove these lines in your project:
https://github.com/WalletConnect/WalletConnectUnity/blob/3b71f8a704b1826a74a724f34a7c0d8e1c5b3a45/Assets/WalletConnectUnity/Scripts/WalletConnectUnity/WCSignClient.cs#L333

https://github.com/WalletConnect/WalletConnectUnity/blob/3b71f8a704b1826a74a724f34a7c0d8e1c5b3a45/Assets/WalletConnectUnity/Scripts/WalletConnectUnity/WalletConnectUnity.cs#L347
