### ISSUE TITLE
custom Eth contract call

### ISSUE THREAD

**Issue by veve178** [WalletConnect/WalletConnectUnity#18]
Is it possible to make eth contract call for various usage, without using Nethereum?

**Comment by ecp4224** [comment]
It's technically possible, you can use `EthSendTransaction` with a custom `data` field to interact with a contract. However, there currently is no clean API to interact with a contract 

If you mean being able to call `view` or `pure` functions in a contract, then the answer is no this is not supported because these calls aren't supported in the WalletConnect protocol. This is why [an external RPC url](https://github.com/WalletConnect/WalletConnectUnity#nethereum) is required when you use the NEthereum extension

**Comment by nhannh-senspark** [comment]
@ecp4224 On Android, I have successfully call the contract using Nethereum. But it doesn't automatically switch to the Metamask app for me to sign. I have to switch apps manually. Do you have any solution.
Example of my code:
`
web3 = WalletConnect.ActiveSession.BuildWeb3(new Uri(uri)).AsWalletAccount(true);
...
var f = GetContract().GetFunction("mint");
var gas = await f.EstimateGasAsync(walletAddress, null, null, count, category);
var receipt = await f.SendTransactionAndWaitForReceiptAsync(walletAddress, gas, null, null, count, category)
`

**Comment by agelessZeal** [comment]
How I can make the custom data to interact with a contract?

**Comment by gigajuwels** [comment]
closed due to v1 depreciation
