### ISSUE TITLE
Use cross-platform lib for cryptography

### ISSUE THREAD

**Issue by jasonboukheir** [WalletConnect/WalletConnectUnity#92]
Great work so far on starting to port the WalletConnectSharp lib to Unity!

I need a WC v2 client that works on mac, windows, linux, android, ios, and webgl. I'm building out my own implementation. Ideally, I just use WalletConnectUnity and don't provide a custom implementation because I don't have time to maintain it. I figure I'd share some of my progress here to spark a discussion and hopefully help move this package forward. You'll need a cross platform cryptography library. Is BouncyCastle Portable truly portable? What are your thoughts on using a native portable library like `libsodium`?

### libsodium

Benefits:
- cross platform
- fast
- no GC pressure
- compatible with Burst compiler

Cons:
- requires managing native plugins for each platform 
- not C#
- difficult to debug native plugins

[See my crypto progress here.](https://github.com/CareBoo/unity-algorand-sdk/tree/c4c267230e046a67efcf238c0d45bf110b30c2f9/Runtime/Algorand.Unity.Crypto)

**Comment by gigajuwels** [comment]
We've had success on Android mobile, Windows and OSX with BouncyCastle Portable. I will be testing on iOS later this week, but I imagine it should work (building BouncyCastle Portable with IL2CPP scripting backend seems to work).
I'd be willing to take a look at your crypto progress, I think this issue may be better suited in the [WalletConnectSharp](https://github.com/WalletConnect/WalletConnectSharp) repo, since that repo will have the `WalletConnect.Crypto` module that is using the BouncyCastle Portable lib.

**Comment by jasonboukheir** [comment]
@gigajuwels thanks for the reply and good thoughts! I'm going to close out this issue, and open a new one under the following conditions:

1. I will test it out on WebGL and see if it works. That one is the hairy one since it can hang on any secret `Task`s.
2. If it works, then I'm not going to make an issue. If it doesn't, then I'm going to make an issue in the `WalletConnectSharp` repo to support emscripten/WebGL (though maybe that's something specific that should be for Unity?)
